In [2]:
    list = [1,2,3]

In [18]:
import numpy as np

In [19]:
arr = np.array(list)

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

# Numpy Array Method


In [21]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [22]:
np.zeros((8,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
np.ones((1,5))

array([[1., 1., 1., 1., 1.]])

In [24]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [25]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
np.random.rand(0,1)

array([], shape=(0, 1), dtype=float64)

In [28]:
np.random.randint(1,100,10)


array([53, 30, 91, 88, 16, 91, 58, 89, 25, 70])

In [29]:
arr = np.arange(25)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
arr.argmin()

0

In [33]:
arr.argmax()

24

In [34]:
ranarr=np.random.randint(3,105,50)

In [39]:
ranarr

array([ 84,  93,  87,  66,  69,   7,  53,  96,  20,  72,  66,  88,  63,
        64,  60,  70,  47,  59,  61,  38,  47,  86,  29,  83,  64,  76,
        36,  64,  60,  89,  57,  43,  49,  96,  16,  85,  66,  92,  14,
        88,  52,  11,  37,  77, 101,  61,  79,  15,  99,  36])

In [40]:
ranarr.max()

101

In [41]:
ranarr.min()

7

In [42]:
ranarr.argmax()

44

In [44]:
ranarr.argmin()

5

In [45]:
ranarr.shape


(50,)

In [47]:
ranarr.dtype

dtype('int64')

# Numpy Indexing and Selection

In [49]:
import numpy as np

In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [58]:
arr2= np.arange(0,100)

In [59]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [60]:
arr[2:8]

array([2, 3, 4, 5, 6, 7])

In [61]:
arr2[:6]

array([0, 1, 2, 3, 4, 5])

In [62]:
arr2[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
       71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87,
       88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [63]:
half_arr2 = arr2[0:51]

In [64]:
half_arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

# 2d array

In [67]:
arr2d= np.array([[1,3,4],[8,2,5],[12,32,45]])

In [68]:
arr2d

array([[ 1,  3,  4],
       [ 8,  2,  5],
       [12, 32, 45]])

In [73]:
arr2d[0]

array([1, 3, 4])

In [74]:
arr2d[1]

array([8, 2, 5])

In [76]:
arr2d[2,2]

45

In [88]:
arr2d[:2,1:]

array([[3, 4],
       [2, 5]])

Boolean

In [81]:
arr=np.arange(1,11)
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
bool_arr=arr>5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [84]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [85]:
arr[arr<5]

array([1, 2, 3, 4])

In [87]:
arr_2d=np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])